/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Tue Jun 25 22:20:49 2019";
extern const char kBuilderName[] = "root";
extern const char kHostName[] = "localhost.localdomain";
extern const char kCompiler[] = "GCC 4.8.5";
}}
