/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit 78ba3376f94594ad646b0f47ac5edad8852097a9\n"
"Author: zhaoyan002018 <879682420@qq.com>\n"
"Date:   Wed Jun 26 08:37:40 2019 +0800\n"
"\n"
"    init\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Tue Jul  9 09:54:26 2019";
extern const char kBuilderName[] = "root";
extern const char kHostName[] = "localhost.localdomain";
extern const char kCompiler[] = "GCC 4.8.5";
}}
