cc_plugin(
	name = "dhcp",
	srcs = ['dhcp.c'],
	warning="no",
	defs=['_MT']
)


cc_plugin(
	name = "http",
	srcs = ['http.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "irc",
	srcs = ['irc.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "krb5",
	srcs = ['krb5.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "ldap",
	srcs = ['ldap.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "misc",
	srcs = ['misc.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "mysql",
	srcs = ['mysql.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "oracle",
	srcs = ['oracle.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "postgresql",
	srcs = ['postgresql.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "quic",
	srcs = ['quic.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "radius",
	srcs = ['radius.c'],
	warning="no",
	defs=['_MT']
)

cc_plugin(
	name = "smb",
	srcs = ['smb.c'],
	warning="no",
	defs=['_MT']
)

cc_plugin(
	name = "smtp",
	srcs = ['smtp.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "socks",
	srcs = ['socks.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "ssh",
	srcs = ['ssh.c'],
	warning="no",
	defs=['_MT']
)
cc_plugin(
	name = "tds",
	srcs = ['tds.c'],
	warning="no",
	defs=['_MT']
)

cc_plugin(
	name = "tls",
	srcs = ['tls.c'],
	warning="no",
	defs=['_MT']
)
