cc_plugin(
	name = "netflow",
	srcs = ['netflow.c'],
	warning = "no",
	defs=['_MT'],
)

cc_plugin(
	name = "scrubspi",
	srcs = ['scrubspi.c'],
	warning = "no",
	defs=['_MT'],
)
cc_plugin(
	name = "suricata",
	srcs = ['suricata.c'],
	warning = "no",
	defs=['_MT'],
)
cc_plugin(
	name = "tagger",
	srcs = ['tagger.c'],
	warning = "no",
	defs=['_MT'],
)
cc_plugin(
	name = "wise",
	srcs = ['wise.c'],
	warning = "no",
	defs=['_MT'],
)
cc_plugin(
	name = "writer-s3",
	srcs = ['writer-s3.c'],
	warning = "no",
	defs=['_MT'],
)


