#pragma once
typedef enum {
	IPTYPE_ON_NETWORK,
	IPTYPE_PRIVATE,
	IPTYPE_SHARED,
	IPTYPE_LOOKBACK,
	IPTYPE_LOCAL,
	IPTYPE_IETF,
	IPTYPE_TEST,
	IPTYPE_ANYCAST,
	IPTYPE_AMT,
	IPTYPE_BROADCAST,
	IPTYPE_BENCHMARK,
	IPTYPE_MULTICAST,
	IPTYPE_RESERVED,
	IPTYPE_INTERNET
} IPTYPE;
